#ifndef APPSTATE_H
#define APPSTATE_H

enum AppState {
    SCREEN_WELCOME,
    SCREEN_ROLE,

    SCREEN_READER_LOGIN,
    SCREEN_READER_REGISTER,
    SCREEN_READER_MENU,

    SCREEN_LIB_LOGIN,
    SCREEN_LIB_MENU,

    SCREEN_SEARCH_BOOK,
    SCREEN_VIEW_BOOK,
    SCREEN_BORROW_BOOK,
    SCREEN_RETURN_BOOK,
    SCREEN_RATE_BOOK,
    SCREEN_TOP_BOOK,
    SCREEN_HISTORY,

    SCREEN_VIEW_READER,

    SCREEN_LIB_ADD,
    SCREEN_LIB_DELETE,
    SCREEN_LIB_UPDATE,
    SCREEN_READER_CHOICE
};

#endif