#ifndef STATE_HPP
#define STATE_HPP

enum class AppState {
    SPLASH,
    HOME,
    CATEGORY,
    BOOK_DETAIL,
    LOGIN_CHOICE,
    LOGIN_READER,
    LOGIN_LIBRARIAN,
    REGISTER_READER,
    READER_CARD,
    BORROWED_BOOKS,
    RETURN_BOOKS,
    RATING_BOOK,
    READER_BORROWED_BOOKS,
    READER_HISTORY,
    LIBRARIAN_CARD,
    ADD_BOOKS,
    MANAGE_BOOKS,
    MANAGE_READERS,
    STATISTICS
};

#endif